---
- name: Install MySQL (MariaDB) server
  hosts: mysql
  become: yes
  tasks:
    - name: Install MariaDB server (MySQL equivalent)
      yum:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
