---
- name: Install MySQL Server
  hosts: mysql
  become: yes
  tasks:
    - name: Install MySQL
      yum:
        name: mysql-server
        state: present

    - name: Start & enable MySQL service
      service:
        name: mysqld
        state: started
        enabled: yes
